<?php
class JConfig {
	public $offline = false;
	public $offline_message = 'This site is down for maintenance.<br>Please check back again soon.';
	public $display_offline_message = 1;
	public $offline_image = '';
	public $sitename = 'Localhost';
	public $editor = 'tinymce';
	public $captcha = '0';
	public $list_limit = 20;
	public $access = 1;
	public $debug = 1;
	public $debug_lang = false;
	public $debug_lang_const = true;
	public $dbtype = 'mysqli';

	// public $host = '10.49.41.172:3308';
	// public $user = 'dba';
	// public $password = 'Abc123@@@';
	// public $db = 'joomla511';

	public $host = '10.49.41.247:3306';
	public $user = 'pxdnict';
	public $password = 'PX@2024!@#';
	public $db = 'phuongxa_2025';

	// public $host = '10.49.45.13:3306';
	// public $user = 'cbccdang';
	// public $password = 'cbccdang';
	// public $db = 'cbcc_khoidang';
	public $dbprefix = 'jos_';
	public $dbencryption = 0;
	public $dbsslverifyservercert = false;
	public $dbsslkey = '';
	public $dbsslcert = '';
	public $dbsslca = '';
	public $dbsslcipher = '';
	public $force_ssl = 0;
	public $live_site = '';
	public $secret = 'lyLzrdqHJxAmdlg6';
	public $gzip = false;
	public $error_reporting = 'default';
	public $helpurl = 'https://help.joomla.org/proxy?keyref=Help{major}{minor}:{keyref}&lang={langcode}';
	public $offset = 'UTC';
	public $mailonline = true;
	public $mailer = 'mail';
	public $mailfrom = 'huenn.dnict@gmail.com';
	public $fromname = 'Localhost';
	public $sendmail = '/usr/sbin/sendmail';
	public $smtpauth = false;
	public $smtpuser = '';
	public $smtppass = '';
	public $smtphost = 'localhost';
	public $smtpsecure = 'none';
	public $smtpport = 25;
	public $caching = 0;
	public $cache_handler = 'file';
	public $cachetime = 15;
	public $cache_platformprefix = false;
	public $MetaDesc = '';
	public $MetaAuthor = true;
	public $MetaVersion = false;
	public $robots = '';
	public $sef = true;
	public $sef_rewrite = false;
	public $sef_suffix = false;
	public $unicodeslugs = false;
	public $feed_limit = 10;
	public $feed_email = 'none';
	public $log_path = 'F:\\xampp82\\htdocs\\Joomla_511\\logs';
	public $tmp_path = 'F:\\xampp82\\htdocs\\Joomla_511\\tmp';
	public $lifetime = 15;
	public $session_handler = 'database';
	public $shared_session = false;
	public $session_metadata = true;
}